// LOGIN ACTIONS
export const ON_CHANGE_EMAIL = 'ON_CHANGE_EMAIL';
export const ON_CHANGE_PASSWORD = 'ON_CHANGE_PASSWORD';

// SIGNUP ACTIONS
export const ON_CHANGE_PICTURE = 'ON_CHANGE_PICTURE';
export const ON_CHANGE_NAME = 'ON_CHANGE_NAME';
export const ON_CHANGE_NEW_EMAIL = 'ON_CHANGE_NEW_EMAIL';
export const ON_CHANGE_NEW_PASSWORD = 'ON_CHANGE_NEW_PASSWORD';
